### PR TITLE
Update logs.pp

### PR DESCRIPTION
**Pull request by michaeljmonte**
Added support for the log_line_prefix config setting.

### CODE REVIEW

**Review by mwhahaha — CHANGES_REQUESTED** [review]
Please use spaces and not tabs

**Comment by michaeljmonte** [comment]
Updated with requested changes.

**Review by mwhahaha — CHANGES_REQUESTED** [review]
Looks fine. However can you please squash the two changes together?  Thanks

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by mwhahaha** [comment]
actually never mind, i can squash it

**Pull request merged**
