### PR TITLE
Use the correct key for setting if_cmd_path

### PR DESCRIPTION
**Pull request by brummett**
This sets the path for the if_up_cmd and if_down_cmd

### CODE REVIEW

**Comment by mwhahaha** [comment]
This appears to already captured in #18, should I just merge that instead?

**Comment by brummett** [comment]
Probably.

I just started using pgpool, so I didn't know `if_cmd_path` was a recent addition.  I thought the `ifconfig_path` key that was there was just a typo or something.

**Comment by mwhahaha** [comment]
ifconfig_path was the old one (~3.3 or something). I haven't deployed pgpool or touched this module in some time so If you want to test #18 and let me know if that works for you I can merge that instead

**Comment by brummett** [comment]
Yes, #18 worked for me.  It still writes out an `ifconfig_path` config entry, but that doesn't seem to cause any problems.

**Comment by mwhahaha** [comment]
Ok I merged #18 so closing this one

**Pull request closed without merging**
