### PR TITLE
rename hba::method to hba::auth_method like in postgresql pg_hba

### PR DESCRIPTION
**Pull request by oscarsix**

### CODE REVIEW

**Comment by mwhahaha** [comment]
This is a breaking change for anyone already using this.  I'm not really inclined to rename this variable because it also aligns with the pg_hba resource we are leveraging.

**Comment by antaflos** [comment]
@mwhahaha Would you accept a PR that makes this change in a backwards compatible manner, so that users can use either `hba::method` or `hba::auth_method`, which then gets passed to `pg_hba`'s `method` parameter?

The reason for this change is mostly cosmetic but also to increase consistency with PostgreSQL's documentation as well as compatibility with puppetlabs/puppetlabs-postgresql's implementation of `pg_hba_rule` (which uses `auth_method`).

IMO it is a bug in hercules-team/augeasproviders_postgresql that the parameter is named `method` instead of `auth_method`.

**Comment by mwhahaha** [comment]
@antaflos, yes backwards compatibility is a must. I would gladly accept one that handles both.

**Comment by antaflos** [comment]
@mwhahaha I have created PR #10, please have a look. The logic is fairly simple but I have not yet tested this on a real Pgpool setup.

**Comment by mwhahaha** [comment]
Closing this in favor of #10.

**Pull request closed without merging**
